name: "Deploy to Nuget"

on:
  push:
    tags:
      - 'v*'

env:
  PROJECT_PATH: 'src/Forbid/Forbid.csproj'
  TEST_PROJECT_PATH: 'tests/Forbid.UnitTests/Forbid.UnitTests.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  SOURCE_URL: https://api.nuget.org/v3/index.json
  BUILD_CONFIGURATION: Release

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}

      - name: Test
        run: dotnet test ${{ env.TEST_PROJECT_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }}

      - name: Get Version
        id: version
        uses: battila7/get-version-action@v2

      - name: Pack
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration ${{ env.BUILD_CONFIGURATION }} -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: Push
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.SOURCE_URL }} --skip-duplicate
